Repository javier-aguilar/brownfield-of-dreams, pull requests merged in 2020-05, with the labels that each got.

#18 User Dashboard - GitHub Repos
  .ruby-version
  .travis.yml
  app/models/github.rb
  app/models/user.rb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20200505224554_add_token_to_users.rb
  db/schema.rb
  spec/features/user/user_dashboard_spec.rb
Labels: enhancement

#19 Add feature tests
  .ruby-version
  .travis.yml
  Gemfile
  Gemfile.lock
  spec/features/user/user_dashboard_spec.rb
Labels: enhancement

#23 Github Section: Add Followers/Following
  app/controllers/users_controller.rb
  app/facades/user_facade.rb
  app/models/github.rb
  app/models/github/follower.rb
  app/models/github/repo.rb
  app/models/user.rb
  app/services/github_service.rb
  app/views/users/show.html.erb
  spec/features/user/user_dashboard_spec.rb
  spec/features/vistors/visitor_can_register_spec.rb
  spec/modules/follower_spec.rb
  spec/modules/github_spec.rb
  spec/modules/repo_spec.rb
  spec/services/github_service_spec.rb
Labels: enhancement

#27 Friendships: User can add friend
  app/controllers/friends_controller.rb
  app/controllers/githubs_controller.rb
  app/models/friendship.rb
  app/models/github.rb
  app/models/github/follower.rb
  app/models/github/user.rb
  app/models/user.rb
  app/services/github_service.rb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20200512011723_add_uid_to_users.rb
  db/migrate/20200512225820_create_friendships.rb
  db/schema.rb
  spec/features/user/user_can_add_friend_spec.rb
  spec/fixtures/vcr_cassettes/User/can_add_friend.yml
  spec/fixtures/vcr_cassettes/User/cannot_add_friend_with_invalid_id.yml
  spec/modules/github_user_spec.rb
Labels: enhancement

#29 Tutorial: Delete videos associated with tutorial
  app/models/tutorial.rb
  app/views/admin/dashboard/show.html.erb
  spec/features/admin/admin_can_delete_tutorial_spec.rb
Labels: bug

#30 Bookmarks: Display
  app/controllers/application_controller.rb
  app/controllers/friends_controller.rb
  app/controllers/user_videos_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/models/you_tube/video.rb
  app/services/youtube_service.rb
  app/views/tutorials/show.html.erb
  app/views/users/show.html.erb
  db/schema.rb
  spec/features/user/user_can_bookmark_a_video_spec.rb
  spec/features/user/user_can_see_bookmark_spec.rb
  spec/features/vistors/visitor_is_asked_to_log_in_when_bookmarking_spec.rb
  spec/fixtures/vcr_cassettes/When_I_visit_/admin/tutorials/new/I_can_import_a_YouTube_playlist_by_filling_a_form.yml
  spec/fixtures/vcr_cassettes/When_I_visit_/admin/tutorials/new/I_receive_an_error_when_trying_to_import_a_YouTube_playlist_with_invalid_token.yml
Labels: bug, enhancement
